DROP DATABASE IF EXISTS CitationDB;
CREATE DATABASE CitationDB;
DROP DATABASE IF EXISTS QueryStoreDB;
CREATE DATABASE QueryStoreDB;
DROP DATABASE IF EXISTS PersistentIdentifierDB;
CREATE DATABASE PersistentIdentifierDB;
DROP DATABASE IF EXISTS CitationUserDB;

